name: soccer-sensor
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - black
  - mypy
  - ipykernel
  - openpyxl
  - dataclasses
  - matplotlib
  - statsmodels
  - seaborn
  - fancyimpute